name: expanse_manager
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.0
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  persistent_bottom_nav_bar: ^5.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4
  fluttertoast: ^8.2.2
  firebase_database: ^10.2.3
  image_picker: ^1.0.2
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
    - assets/designs/images/cloth2.png
    - assets/designs/images/auto-group-xsa5.png
    - assets/designs/images/shadows-bg.png
    - assets/designs/images/icon-chevron-down.png
    - assets/designs/images/group-8.png
    - assets/designs/images/color.png
    - assets/designs/images/auto-group-jhwv.png
    - assets/designs/images/auto-group-utzh.png
    - assets/designs/images/arrow-up-bg.png
    - assets/designs/images/auto-group-c5mw.png
    - assets/designs/images/bg-arrow-down-bg.png
    - assets/designs/images/pants2.png
    - assets/designs/images/combined-shape.png
    - assets/designs/images/auto-group-xnaz.png
    - assets/designs/images/auto-group-laq5.png
    - assets/designs/images/auto-group-qmmw.png
    - assets/designs/images/bg-arrow-up-bg.png
    - assets/designs/images/auto-group-zot3.png
    - assets/designs/images/auto-group-9vxf.png
    - assets/designs/images/ellipse-7.png
    - assets/designs/images/eyes.png
    - assets/designs/images/auto-group-sxkr.png
    - assets/designs/images/cloth.png
    - assets/designs/images/glasses.png
    - assets/designs/images/user-1-1.png
    - assets/designs/images/group-15.png
    - assets/designs/images/auto-group-hqch.png
    - assets/designs/images/ellipse-8.png
    - assets/designs/images/battery.png
    - assets/designs/images/image-6.png
    - assets/designs/images/group-14.png
    - assets/designs/images/icon-chevron-down-7Wh.png
    - assets/designs/images/frame-5.png
    - assets/designs/images/home-1.png
    - assets/designs/images/combined-shape-iUH.png
    - assets/designs/images/shoes.png
    - assets/designs/images/orange-donut-bg.png
    - assets/designs/images/group-16.png
    - assets/designs/images/group-11.png
    - assets/designs/images/specular.png
    - assets/designs/images/image-5.png
    - assets/designs/images/lips.png
    - assets/designs/images/group-11-zMf.png
    - assets/designs/images/group-13.png
    - assets/designs/images/combined-shape-H4u.png
    - assets/designs/images/group-11-w5K.png
    - assets/designs/images/group-18.png
    - assets/designs/images/bx-sort-1.png
    - assets/designs/images/background-primary-bg.png
    - assets/designs/images/background-primary-bg-pd7.png
    - assets/designs/images/background-primary-bg-mHT.png
    - assets/designs/images/hair.png
    - assets/designs/images/background-primary-bg-JHP.png
    - assets/designs/images/rectangle-9.png
    - assets/designs/images/battery-BMB.png
    - assets/designs/images/image-13.png
    - assets/designs/images/image-15.png
    - assets/designs/images/image-6-xXK.png
    - assets/designs/images/pink-donut-bg.png
    - assets/designs/images/image-14.png
    - assets/designs/images/group-12.png
    - assets/designs/images/combined-shape-r4h.png
    - assets/designs/images/download-alt-1.png
    - assets/designs/images/icon-plus-circle.png
    - assets/designs/images/frame-7.png
    - assets/designs/images/icon-calendar.png
    - assets/designs/images/delete.png
    - assets/designs/images/base-bg.png
    - assets/designs/images/dollar-bg.png
    - assets/designs/images/background-primary-bg-nnd.png
    - assets/designs/images/combined-shape-Tww.png
    - assets/designs/images/group-2.png
    - assets/designs/images/battery-HJH.png
    - assets/designs/images/frame-4.png
    - assets/designs/images/bar-chart-1.png
    - assets/designs/images/arrow-down-bg.png
    - assets/designs/images/pants.png
    - assets/designs/images/rectangle-16.png
    - assets/designs/images/frame-4-9SH.png
    - assets/designs/images/wallet-1.png
    - assets/designs/images/bar-chart-fill-1.png
    - assets/designs/images/vector-2.png
    - assets/designs/images/background-primary-bg-kpR.png
    - assets/designs/images/frame-21.png
    - assets/designs/images/icon-chevron-left.png
    - assets/designs/images/vector-1.png
    - assets/designs/images/blue-donut-bg.png
    - assets/designs/images/purple-donut-bg.png
    - assets/designs/images/bg-dollar-bg.png
    - assets/designs/images/group-6.png
    - assets/designs/images/background-primary-bg-iPs.png
    - assets/designs/images/shield-checkered-fill-1.png
    - assets/designs/images/ring-bg.png
    - assets/designs/images/icon-chevron-down-qaH.png
    - assets/designs/images/blur-behind.png
    - assets/designs/images/battery-BJR.png
    - assets/designs/images/auto-group-qcy3.png
    - assets/designs/images/.png
    - assets/designs/images/image-6-RJZ.png
    - assets/designs/images/combined-shape-VLM.png
    - assets/designs/images/skin.png
    - assets/designs/images/battery-RR3.png
    - assets/designs/images/frame-21-to3.png
    - assets/designs/images/combined-shape-qTP.png
    - assets/designs/images/background-primary-bg-z5P.png
    - assets/designs/images/background-primary-bg-q61.png
    - assets/designs/images/icon-chevron-left-kGZ.png
    - assets/designs/images/combined-shape-4o3.png
    - assets/designs/images/group-19.png
    - assets/designs/images/combined-shape-CGH.png
    - assets/designs/images/combined-shape-wdB.png
    - assets/designs/images/user-1-1-fjX.png
    - assets/designs/images/rectangle.png
    - assets/designs/images/users-fill-1.png
    - assets/designs/images/user-fill-1.png
    - assets/designs/images/wallet-1-D8u.png
    - assets/designs/images/icon-chevron-left-wKo.png
    - assets/designs/images/group-6-jWZ.png
    - assets/designs/images/icon-chevron-left-LTb.png
    - assets/designs/images/frame-21-xoj.png
    - assets/designs/images/user-fill-1-QnV.png
    - assets/designs/images/wallet-fill.png
    - assets/designs/images/envelope-simple-fill-1.png
    - assets/designs/images/frame-4-7gD.png
    - assets/designs/images/home-1-4E5.png
    - assets/designs/images/bar-chart-1-y1b.png
    - assets/designs/images/group-6-ACH.png
    - assets/designs/images/group-11-fNR.png
    - assets/designs/images/home-1-4vM.png
    - assets/designs/images/color-CZP.png
    - assets/designs/images/image-5-KxV.png
    - assets/designs/images/lock-key-fill-1.png
    - assets/designs/images/wallet-fill-dzH.png
    - assets/designs/images/rectangle-9-Fgm.png
    - assets/designs/images/frame-21-WyP.png
    - assets/designs/images/frame-21-1z1.png
    - assets/designs/images/bar-chart-1-e3K.png
    - assets/designs/images/combined-shape-Nzu.png
    - assets/designs/images/rectangle-9-jaZ.png
    - assets/designs/images/rectangle-9-hGV.png
    - assets/designs/images/image-13-htV.png
    - assets/designs/images/frame-4-DM3.png
    - assets/designs/images/frame-21-mJ1.png
    - assets/designs/images/user-1-1-YzD.png
    - assets/designs/images/battery-jKF.png
    - assets/designs/images/combined-shape-HtV.png
    - assets/designs/images/icon-chevron-left-nPK.png
    - assets/designs/images/image-6-XjX.png
    - assets/designs/images/group-6-xqX.png
    - assets/designs/images/image-16.png
    - assets/designs/images/form-bg.png
    - assets/designs/images/decorativeline.png
    - assets/designs/images/rectangle-9-RLu.png
    - assets/designs/images/user-1-1-JBj.png
    - assets/designs/images/frame-4-d7X.png
    - assets/designs/images/bar-chart-1-Zaq.png
    - assets/designs/images/combined-shape-Gk9.png
    - assets/designs/images/frame-9.png
    - assets/designs/images/frame-9-EzM.png
    - assets/designs/images/home-1-Dsw.png
    - assets/designs/images/visa.png
    - assets/designs/images/icon-chevron-left-rKb.png
    - assets/designs/images/emv-chip.png
    - assets/designs/images/shape.png
    - assets/designs/images/emv-chip-9D3.png
    - assets/designs/images/icon-chevron-left-Kz1.png
    - assets/designs/images/wallet-fill-Nj3.png
    - assets/designs/images/battery-fvy.png
    - assets/designs/images/rectangle-9-YCZ.png
    - assets/designs/images/logo-paypal-1.png
    - assets/designs/images/group-6-JdP.png
    - assets/designs/images/glossy.png
    - assets/designs/images/bank-fill-1.png
    - assets/designs/images/icon-chevron-left-u5K.png
    - assets/designs/images/frame-4-ouB.png
    - assets/designs/images/group-6-f3f.png
    - assets/designs/images/bar-chart-1-bYm.png
    - assets/designs/images/user-1-1-FdK.png
    - assets/designs/images/user-1-1-End.png
    - assets/designs/images/combined-shape-o2R.png
    - assets/designs/images/battery-9MB.png
    - assets/designs/images/battery-785.png
    - assets/designs/images/combined-shape-wFX.png
    - assets/designs/images/wallet-fill-wYM.png
    - assets/designs/images/wallet-fill-f8D.png
    - assets/designs/images/icon-chevron-up.png
    - assets/designs/images/currency-circle-dollar-fill-1.png
    - assets/designs/images/combined-shape-XH3.png
    - assets/designs/images/combined-shape-2zV.png
    - assets/designs/images/bar-chart-1-7uT.png
    - assets/designs/images/image-13-eKK.png
    - assets/designs/images/check-circle-fill-1.png
    - assets/designs/images/home-1-yku.png
    - assets/designs/images/group-19-oj7.png
    - assets/designs/images/home-1-2GR.png
    - assets/designs/images/rectangle-BzH.png
    - assets/designs/images/rectangle-9-vau.png
    - assets/designs/images/combined-shape-QaV.png
    - assets/designs/images/icon-chevron-up-dzy.png
    - assets/designs/images/combined-shape-Azu.png
    - assets/designs/images/group-6-zim.png
    - assets/designs/images/combined-shape-Qfj.png
    - assets/designs/images/home-1-qds.png
    - assets/designs/images/credit-card-fill-1.png
    - assets/designs/images/user-1-1-f8u.png
    - assets/designs/images/group-19-QfK.png
    - assets/designs/images/rectangle-9-LR7.png
    - assets/designs/images/wallet-fill-NLR.png
    - assets/designs/images/logo-paypal-1-jZb.png
    - assets/designs/images/icon-chevron-left-bCu.png
    - assets/designs/images/group-24.png
    - assets/designs/images/home-1-5ey.png
    - assets/designs/images/icon-chevron-left-t1P.png
    - assets/designs/images/combined-shape-iVX.png
    - assets/designs/images/bar-chart-1-xwT.png
    - assets/designs/images/wallet-fill-Pds.png
    - assets/designs/images/group-6-DfP.png
    - assets/designs/images/battery-mB7.png
    - assets/designs/images/image-6-RqK.png
    - assets/designs/images/user-1-1-kvm.png
    - assets/designs/images/combined-shape-rtZ.png
    - assets/designs/images/group-23.png
    - assets/designs/images/rectangle-MLV.png
    - assets/designs/images/group-19-UR7.png
    - assets/designs/images/decorativeline-px9.png
    - assets/designs/images/bar-chart-1-DUD.png
    - assets/designs/images/group-19-sof.png
    - assets/designs/images/battery-Jgq.png
    - assets/designs/images/icon-chevron-left-mkm.png
    - assets/designs/images/battery-1RT.png
    - assets/designs/images/user-1-1-p8R.png
    - assets/designs/images/group-11-uVj.png
    - assets/designs/images/wallet-fill-tVP.png
    - assets/designs/images/group-6-93w.png
    - assets/designs/images/home-1-QZP.png
    - assets/designs/images/group-6-HvZ.png
    - assets/designs/images/combined-shape-Xpu.png
    - assets/designs/images/combined-shape-bKP.png
    - assets/designs/images/image-6-x3T.png
    - assets/designs/images/rectangle-9-nJV.png
    - assets/designs/images/bar-chart-1-J1f.png
    - assets/designs/images/icon-chevron-left-tad.png
    - assets/designs/images/copy-simple-fill-1.png
    - assets/designs/images/bar-chart-1-eqX.png
    - assets/designs/images/rectangle-9-5HK.png
    - assets/designs/images/home-1-UUZ.png
    - assets/designs/images/combined-shape-xrD.png
    - assets/designs/images/combined-shape-GFj.png
    - assets/designs/images/rectangle-9-EQy.png
    - assets/designs/images/rectangle-9-kBK.png
    - assets/designs/images/wallet-fill-X9T.png
    - assets/designs/images/icon-chevron-up-pRw.png
    - assets/designs/images/user-1-1-yyK.png
    - assets/designs/images/home-1-2w3.png
    - assets/designs/images/battery-hpd.png
    - assets/designs/images/check-circle-fill-1-a1F.png
    - assets/designs/images/group-6-kLR.png
    - assets/designs/images/group-19-XA9.png
    - assets/thumbnail/images/combined-shape-wow.png
    - assets/thumbnail/images/screen-1.png
    - assets/thumbnail/images/screen-3.png
    - assets/thumbnail/images/screen-2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
